#!/bin/bash
echo "The backup made before installation will now be restored..."
cd "/"
echo "Restoring files from /Library/Application Support/ClassicAppleBoot..."
sudo mv -f "/Library/Application Support/ClassicAppleBoot/apple-logo-black-n84@2x~iphone.png" "/Sytem/Library/PrivateFrameworks/ProgressUI.framework/" || set -e && echo "Failed to restore backup!"
sudo mv -f "/Library/Application Support/ClassicAppleBoot/apple-logo-black@2x~iphone.png" "/Sytem/Library/PrivateFrameworks/ProgressUI.framework/" || set -e && echo "Failed to restore backup!"
echo "Removing backup folder..."
sudo rmdir "/Library/Application Support/ClassicAppleBoot/" || set -e && echo "Failed to remove directory!"
echo "Finished restoring the backup!"